### ISSUE TITLE
Garbage byte in device ID, when two or more device IDs are specified

### ISSUE THREAD

**Issue by user20120112** [yifanlu/KindleTool#1]
Given empty directory _data_, command

``` shell
kindletool create ota2 -d k5w -d k5g data update.bin
```

produces update bundle, where device ID for Kindle Touch 3G isn't **0F 00**, but rather **0F 05**

I'm using pre-compiled kindletool version (from kindletool.zip distribution archive of Kindle Tool v1.0) under Cygwin on Windows Vista

**Comment by yifanlu** [comment]
I think it is fixed in the latest build.
