### ISSUE TITLE
Device ID 0x10 for Kindle Touch (WiFi-only) could be wrong

### ISSUE THREAD

**Issue by user20120112** [yifanlu/KindleTool#2]
OTA2 update bundles created with **-d k5w** options has **10 00** as relevant device ID. But such a bundle isn't recognized by Kindle Touch (WiFi-only) as valid and bundle is deleted after Kindle USB-disk is detached from computer.

Bundle with device ID **11 00** (i.e. 0x11) is recognized by KT (WiFi-only) as valid.

**Comment by yifanlu** [comment]
Changed device id to 0x11.
