### ISSUE TITLE
unable to extract lastest update file

### ISSUE THREAD

**Issue by ghost** [yifanlu/KindleTool#4]
When I try to extract update_kindle_all_new_paperwhite_5.12.4.bin, it outputs
Bundle         SP01
Cert number    2
Cert file      pubprodkey02.pem
Bundle         FB03
Unknown update bundle version!
Error converting update.

**Comment by NiLuJe** [comment]
That's because the currently active fork is at https://github.com/NiLuJe/KindleTool
